name: FIN.IT API

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.APPLICATION }}/${{ secrets.APPLICATION }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
          
      - name: Configure Docker Authorization
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker Image to Artifact Registry
        run: docker push $IMAGE_NAME

      - name: Deploy Docker Image to Google Cloud Run
        run: |
            gcloud run deploy ${{ secrets.APPLICATION }} \
              --image $IMAGE_NAME \
              --region us-central1 \
              --platform managed \
              --allow-unauthenticated \
              --port  8080
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GCP_KEY: ${{ secrets.GCP_KEY }}
          GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
          GCP_EMAIL: ${{ secrets.GCP_EMAIL }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
